name: odelia
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - simpleitk
  - pydicom
  - pandas
  - numpy
  - tqdm
  - openpyxl
  - torchio
  - pytorch-cuda=11.7
  - pytorch 
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - monai
  - pytorch-lightning=1.9.0
  - tensorboard 
  - scikit-learn
  - matplotlib
  - seaborn 
  - tensorboard